### ISSUE TITLE
Please add tagged releases

### ISSUE THREAD

**Issue by Ichimonji10** [nimble-code/Spin#1]
No tagged releases are present on GitHub. This makes packaging and distributing spin harder. If one of the existing commits in this repository corresponds to a release, please tag it appropriately. Otherwise, make sure to add a tag when the next release is made. Note that releases cannot be fetched directly from spinroot.com, as it's protected by cloudflare, which makes automated curl/wget/etc requests more difficult.

Note that git provides "lightweight" tags and "annotated" tags. The latter should be used for releases, as they retain authorship information (for answering the questions "who created this tag, when, and why?"), and can be signed. Git's CLI tools also treat the two types of tags differently, e.g. certain tools will only show annotated tags by default.

**Comment by nimble-code** [comment]
will fix this and add releases

**Comment by nimble-code** [comment]
Done -- Spin Version 6.5.0 is the first tagged release.
