### ISSUE TITLE
How do I run `iSpin`?

### ISSUE THREAD

**Issue by maxvonhippel** [nimble-code/Spin#13]
The installation instructions on `spinroot.com` appear to be outdated, pointing to a `iSpin` directory which does not exist in this project.  I do find `optional_guii/ispin.tcl`, and I installed `tcl`, but when I run `tclsh ispin.tcl` I get:

> invalid command name "wm"
    while executing
"wm title . "ispin""
    (file "ispin.tcl" line 11)

I am on the latest version of Linux Mint; any help is much appreciated.

**Comment by nimble-code** [comment]
you can just make ispin.tcl executable (or put in in /usr/local/bin/ispin and make it executable.
or, if you want to start it manually, say: wish ispin.tcl
