### ISSUE TITLE
Same issue as #9

### ISSUE THREAD

**Issue by kyechou** [nimble-code/Spin#15]
The same problem arises after the commit 7efa1523e3318618b70d42035bdc1ffeeb3007c7, especially due to the following changes.
- https://github.com/nimble-code/Spin/commit/7efa1523e3318618b70d42035bdc1ffeeb3007c7#diff-cc44c1fa09f86ac73973243b3e688f03
- https://github.com/nimble-code/Spin/commit/7efa1523e3318618b70d42035bdc1ffeeb3007c7#diff-1b25383cca4cd2d5aaa74a9d7f04b354

The issue was solved by #10, so it'd be great if #10 can be rebased or somehow merged to the master branch.

**Comment by nimble-code** [comment]
must have overlooked this one
fixed in 6.5.2
