### ISSUE TITLE
spinroot.com unavailable because of the captcha

### ISSUE THREAD

**Issue by throwaway3feb19** [nimble-code/Spin#2]
Hello,

I didn't find a way to contact the webmaster of spinroot.com.
I'm using this issue tracker to tell you that I am unable to reach spinroot.com because of Cloudflare's reCaptcha which loops indefinitely here. This can happen when e.g. disabling third party cookies.
This makes this Spin hard to approach since all the related resources are there. The limited workaround is to use archive.org to read the website.

Would you consider letting visitors visit the website without solving captchas by disabling DDoS protection on CloudFlare?
Thanks!

**Comment by nimble-code** [comment]
I've added a tarball with the manpages from the spinroot website, and I've added the executables that are normally found there. That should resolve most of the issues (though not all, re background papers etc.)
Don't control the webhost so I can't do much about the captcha issue alas.
