### ISSUE TITLE
array inside typedef

### ISSUE THREAD

**Issue by albertnetymk** [nimble-code/Spin#21]
With the following model, `spin test.pml` only executes two prints, while I was expecting four prints. After reading the documentations on array and typedef, it's not super clear to me whether such behavior is intentional or not.

```
typedef Obj {
  byte children[4]
}

Obj objs[2] = 0

init {
  byte i
  for (i in objs[0].children) {
    printf("%d\n", i)
  }
}
```

**Comment by nimble-code** [comment]
that's a bug. the output is the same if you say "for (i in objs)" so it's clearly not finding the right array here.  i'll look into it and fix it
thanks for the bug report!

**Comment by nimble-code** [comment]
fixed with the last update (version date March 29)

**Comment by albertnetymk** [comment]
Thank you very much.
