### ISSUE TITLE
Consider using GitHub "Releases" for binary downloads

### ISSUE THREAD

**Issue by thomaslee** [nimble-code/Spin#24]
Keeping binaries in the repo may lead to bloat over time & makes it awkward for users to download a specific version of Spin.

Attaching them to a GitHub release instead will eliminate any further bloat & also allow people to download specific versions of Spin binaries without checking out the git repo. It also eliminates any doubt whether the binaries checked into git match the source code as at a specific revision (I don't think they do).

See step 7 over in [Managing releases in a repository](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository).

**Comment by nimble-code** [comment]
will keep this in mind when i do the next formal release.

**Comment by thomaslee** [comment]
appreciate it, thank you!

**Comment by thomaslee** [comment]
Here's an example of a project that I think makes particularly good use of GitHub's "releases" feature if it's a useful reference: https://github.com/kubernetes-sigs/kind/releases

IMO you don't necessarily need to go to the extremes that they do with release notes etc., but note how easy it is to grab a binary for any given release of the software. Super handy if folks run into a bug in a release & need to upgrade/downgrade to mitigate.

**Comment by ye1dos** [comment]
Can you please update information about installation in a website? It only considers .tar and .zip files

**Comment by nimble-code** [comment]
something like: http://spinroot.com/spin/Man/README.html ?
