### ISSUE TITLE
Using -M -k to generate msc-flow by trail file, but generated msc-flow file is not quite right

### ISSUE THREAD

**Issue by M1sstory** [nimble-code/Spin#27]
I generated MSC-Flow through NS protocol trail file, but it had some deviation.
By using the command:
`spin -M -k nscode.pml.trail nscode.pml`
![bc11af6acde69bf1d6e15613f681a5c](https://user-images.githubusercontent.com/29110997/83940328-39c24000-a816-11ea-8616-8c993361e114.png)

The part of results of running the same trail file in ISPIN are as follows。
![image](https://user-images.githubusercontent.com/29110997/83940423-886fda00-a816-11ea-9e80-9b79f998a926.png)

**It is obvious that the process interaction and process names are not aligned.The process interaction part moves to the right relative to the process name, resulting in misalignment.**
@nimble-code

**Comment by nimble-code** [comment]
can you send me that nscode.pml example, so that i can check this out?

**Comment by M1sstory** [comment]
> 你能给我发那个nscode.pml例子，以便我检查一下吗？

Here is the example to verify NS protocols，I think it is a generic problem that applies different code.
[nscode.txt](https://github.com/nimble-code/Spin/files/4742210/nscode.txt)

**Comment by nimble-code** [comment]
Thanks, yes -- the presence of the never claim (derived from the ltl property) appears to cause the message flows with -M to move over one column to far.  I'll fix it and note here when I've uploaded the corrected sourcefile (probably msc_tcl.c only)
thanks for reporting this

**Comment by nimble-code** [comment]
source updated.  6 files changed (main.c mesg.c msc_tcl.c sched.c spin.y and version.h), although only two of those were to fix this issue -- the others are just pending small fixes and code cleanups
