### ISSUE TITLE
iSpin with BFS misses failure state

### ISSUE THREAD

**Issue by sen-uni-kn** [nimble-code/Spin#28]
In the appended model, iSpin reports for BFS that no errors are found.
When we verify the same model with DFS, iSpin actually finds the contained deadlock. 

![TwoPhone_iSpin_Bfs](https://user-images.githubusercontent.com/50913192/86739567-44027480-c036-11ea-9d89-1e3e80c4316d.png)
[TwoPhones.txt](https://github.com/nimble-code/Spin/files/4883309/TwoPhones.txt)

**Comment by nimble-code** [comment]
I'll check it out

**Comment by nimble-code** [comment]
when you run the bfs search from the command line (or from within ispin) you'll see the first line of output has a warning:
$ spin -run -bfs TwoPhones.txt
warning: use of rendezvous with BFS does not preserve all invalid endstates
