### ISSUE TITLE
Passing Content from Channel into external C code

### ISSUE THREAD

**Issue by cvick32** [nimble-code/Spin#29]
Hello, 

  Apologies for posting this here, the SPIN forum is not accepting new members at the moment and I haven't been able to find an answer to this question. 

  I want to have an LTL property that relies on the current messages in a channel. How I've seen this done with data stored in arrays in spin is `c_expr { check(now.array) }`, where `check` is some function defined in C that takes as input the array. I want to something like `c_expr { check(now.channel) }`. I've tried just this but I get an unsigned char in the C code instead of an array which is what I was expecting. I assume that this char is just an identifier for the channel that SPIN uses. Thanks so much for your time, and sorry again if this is the wrong place to post questions like this. I'd be happy to delete this and post again on the forum if need be.

**Comment by nimble-code** [comment]
It's possible to do this, but you'd then have to navigate the internal data structures for channels, which isn't too simple.
you can see how that happens in the function qrecv() that's generated in pan.c (it takes as arguments the channel number, the slot to be checked, and the message field)
easier is probably to just cycle through the channel contents in a d_step in Promela code, and check for the things you need. 
something like:
d_step {
   int cnt = len(q);
   do
   :: cnt >= 0 -> cnt--; q?m; ...check m...; q!m // take from front, add back at the end
   :: else -> break
   od
   skip; // to avoid syntax error
}

**Comment by nimble-code** [comment]
ah, but that doesn't work if you need a single expression that returns true or false of course...

**Comment by nimble-code** [comment]
would a channel poll operation help?
http://spinroot.com/spin/Man/poll.html

**Comment by cvick32** [comment]
Thanks for your quick response. 
I think that the polling operation would work, I just wasn't familiar with it. The LTL statement I want to make is basically, "a message `A` will never appear in channel c". From my understanding, the polling operation could check if the message was anywhere in the channel, but my worry is that even if a process was capable of executing the polling operation statement and leading to a state that would violate the property, the process wouldn't take it because it had other options. Is this a legitimate worry or does SPIN guarantee that this will be found if it's possible?

**Comment by nimble-code** [comment]
If there is a possible execution that violates a property, a verification run will find it.
