### ISSUE TITLE
A question about the timing attribute

### ISSUE THREAD

**Issue by JiHunBae** [nimble-code/Spin#32]
Hello. I am learning SPIN. I have a question, so I leave a question. Can I verify the timing property using SPIN? If possible, what resources should I look for?

Thanks so much for your help.

**Comment by nimble-code** [comment]
To see how one may be able to verify real-time properties with Spin, please see this paper:
https://lamport.azurewebsites.net/pubs/charme2005.pdf

**Comment by JiHunBae** [comment]
I will read the paper you informed, thank you for your good answer.
