### ISSUE TITLE
no MinGW Binaries pc_spinXYZ.zip

### ISSUE THREAD

**Issue by kleuker** [nimble-code/Spin#36]
Hi,
Spin offered for many years binaries for MinGW packed like  pc_spin649.zip. 
It is used quite often (google it) and it is very easy to replace one version with another.
Is there any possibility to get pc_spin651.zip?

Best wishes S.

**Comment by nimble-code** [comment]
the 64bit and 32bit windows binaries in the Bin directory here should be mingw compiled binaries,
so you should be able to use any previous pc_spin...zip package that you have and use the new binaries with it...
let me know if that's not the case
