### ISSUE TITLE
Problem with weak fairness

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#38]
I managed to reproduce this bug with Spin version 6.5.2: https://spinroot.com/fluxbb/viewtopic.php?id=156

**Comment by nimble-code** [comment]
can you send the details?

**Comment by jllang** [comment]
I copied the example given in the forum post into the file `bug.pml`:
```
byte n = 0;
active proctype P() { n=1 }
active proctype Q() { n=2 }

ltl test { <>[](n==1) }
```
Then I ran `spin -a bug.pml`, which printed `ltl test: <> ([] ((n==1)))`. After that, I compiled pan by running `gcc -o pan pan.c`.

Now, if I run `./pan -a -N test`, i get the following output:
```
warning: only one claim defined, -N ignored
pan:1: acceptance cycle (at depth 8)
pan: wrote bug.pml.trail

(Spin Version 6.5.2 -- 6 December 2019)
Warning: Search not completed
	+ Partial Order Reduction

Full statespace search for:
	never claim         	+ (test)
	assertion violations	+ (if within scope of claim)
	acceptance   cycles 	+ (fairness disabled)
	invalid end states	- (disabled by never claim)

State-vector 36 byte, depth reached 9, errors: 1
       10 states, stored (15 visited)
        5 states, matched
       20 transitions (= visited+matched)
        0 atomic steps
hash conflicts:         0 (resolved)

Stats on memory usage (in Megabytes):
    0.001	equivalent memory usage for states (stored*(State-vector + overhead))
    0.291	actual memory usage for states
  128.000	memory used for hash table (-w24)
    0.534	memory used for DFS stack (-m10000)
  128.730	total actual memory usage



pan: elapsed time 0 seconds
```
So far, so good. Pan did find the error. But if I run `./pan -a -f -N test`, I get the following output:
```
warning: only one claim defined, -N ignored

(Spin Version 6.5.2 -- 6 December 2019)
	+ Partial Order Reduction

Full statespace search for:
	never claim         	+ (test)
	assertion violations	+ (if within scope of claim)
	acceptance   cycles 	+ (fairness enabled)
	invalid end states	- (disabled by never claim)

State-vector 36 byte, depth reached 13, errors: 0
       15 states, stored (27 visited)
       20 states, matched
       47 transitions (= visited+matched)
        0 atomic steps
hash conflicts:         0 (resolved)

Stats on memory usage (in Megabytes):
    0.001	equivalent memory usage for states (stored*(State-vector + overhead))
    0.291	actual memory usage for states
  128.000	memory used for hash table (-w24)
    0.534	memory used for DFS stack (-m10000)
  128.730	total actual memory usage


unreached in proctype P
	(0 of 2 states)
unreached in proctype Q
	(0 of 2 states)
unreached in claim test
	_spin_nvr.tmp:10, state 13, "-end-"
	(1 of 13 states)

pan: elapsed time 0 seconds
```
It looks like pan doesn't find the error anymore when weak fairness has been enabled.

**Comment by nimble-code** [comment]
without looking into the details of this -- doesn't this simply mean that the error scenario is not weakly fair?

**Comment by jllang** [comment]
I think all the executions of the system are finite, so neither process can ever starve. But if fairness requires infinite executions, then I guess the model must be unfair.

**Comment by nimble-code** [comment]
it's hard to diagnose what's happening without having an example to study
there could well be a bug, but I can't pin it down without reproducing the behavior first

**Comment by jllang** [comment]
What is wrong with the example above?

**Comment by nimble-code** [comment]
one more observation without looking in more detail:
for LTL verification, every finite execution sequence is mapped to an infinite one where the final state is stuttered forever (this is called the standard stutter extension to extend finite runs to omega-regular runs)

**Comment by topdeckwin** [comment]
Sorry if this is solved/answered elsewhere, but I can still reproduce the error in  [](https://spinroot.com/fluxbb/viewtopic.php?id=156)
using examples directly from the link
`
// demo07.pml
byte n = 0;
active proctype P() { n=1 }
active proctype Q() { n=2 }

ltl test { <>[](n==1) } // should report an error 
`
without weak fairness (works as intended):

`
> spin -run demo07.pml
ltl test: <> ([] ((n==1)))
pan:1: acceptance cycle (at depth 8)
pan: wrote demo07.pml.trail

(Spin Version 6.5.1 -- 3 June 2021)
Warning: Search not completed
        + Partial Order Reduction

Full statespace search for:
        never claim             + (test)
        assertion violations    + (if within scope of claim)
        acceptance   cycles     + (fairness disabled)
        invalid end states      - (disabled by never claim)

State-vector 28 byte, depth reached 9, errors: 1
       10 states, stored (15 visited)
        5 states, matched
       20 transitions (= visited+matched)
        0 atomic steps
hash conflicts:         0 (resolved)

Stats on memory usage (in Megabytes):
    0.001       equivalent memory usage for states (stored*(State-vector + overhead))
    0.291       actual memory usage for states
  128.000       memory used for hash table (-w24)
    0.534       memory used for DFS stack (-m10000)
  128.730       total actual memory usage



pan: elapsed time 0 seconds
`

with weak fairness (failed to detect the error):

`
sumire@Arcus ~/m/CS613_demo (main)> spin -run -f demo07.pml
ltl test: <> ([] ((n==1)))

(Spin Version 6.5.1 -- 3 June 2021)
        + Partial Order Reduction

Full statespace search for:
        never claim             + (test)
        assertion violations    + (if within scope of claim)
        acceptance   cycles     + (fairness enabled)
        invalid end states      - (disabled by never claim)

State-vector 36 byte, depth reached 13, errors: 0
       15 states, stored (27 visited)
       20 states, matched
       47 transitions (= visited+matched)
        0 atomic steps
hash conflicts:         0 (resolved)

Stats on memory usage (in Megabytes):
    0.001       equivalent memory usage for states (stored*(State-vector + overhead))
    0.291       actual memory usage for states
  128.000       memory used for hash table (-w24)
    0.534       memory used for DFS stack (-m10000)
  128.730       total actual memory usage


unreached in proctype P
        (0 of 2 states)
unreached in proctype Q
        (0 of 2 states)
unreached in claim test
        _spin_nvr.tmp:10, state 13, "-end-"
        (1 of 13 states)

pan: elapsed time 0 seconds
`

Another example from the original link that only involves one instance of process so fairness should not have any impact:
`
\\ demo08.pml

byte n=0;

active proctype P() {
  if
  :: n=1
  :: n=2
  fi
}

ltl test { <>[](n==0) } \\ should report error no matter which option is taken
`

without weak fairness (works as intended):
`
> spin -run demo08.pml
ltl test: <> ([] ((n==0)))
pan:1: acceptance cycle (at depth 4)
pan: wrote demo08.pml.trail

(Spin Version 6.5.1 -- 3 June 2021)
Warning: Search not completed
        + Partial Order Reduction

Full statespace search for:
        never claim             + (test)
        assertion violations    + (if within scope of claim)
        acceptance   cycles     + (fairness disabled)
        invalid end states      - (disabled by never claim)

State-vector 20 byte, depth reached 5, errors: 1
        3 states, stored
        0 states, matched
        3 transitions (= stored+matched)
        0 atomic steps
hash conflicts:         0 (resolved)

Stats on memory usage (in Megabytes):
    0.000       equivalent memory usage for states (stored*(State-vector + overhead))
    0.291       actual memory usage for states
  128.000       memory used for hash table (-w24)
    0.534       memory used for DFS stack (-m10000)
  128.730       total actual memory usage



pan: elapsed time 0 seconds
`

with weak fairness (failed to detect error):
`
> spin -run -f demo08.pml
ltl test: <> ([] ((n==0)))

(Spin Version 6.5.1 -- 3 June 2021)
        + Partial Order Reduction

Full statespace search for:
        never claim             + (test)
        assertion violations    + (if within scope of claim)
        acceptance   cycles     + (fairness enabled)
        invalid end states      - (disabled by never claim)

State-vector 28 byte, depth reached 7, errors: 0
        7 states, stored (15 visited)
       14 states, matched
       29 transitions (= visited+matched)
        0 atomic steps
hash conflicts:         0 (resolved)

Stats on memory usage (in Megabytes):
    0.000       equivalent memory usage for states (stored*(State-vector + overhead))
    0.291       actual memory usage for states
  128.000       memory used for hash table (-w24)
    0.534       memory used for DFS stack (-m10000)
  128.730       total actual memory usage


unreached in proctype P
        (0 of 5 states)
unreached in claim test
        _spin_nvr.tmp:10, state 13, "-end-"
        (1 of 13 states)

pan: elapsed time 0 seconds
`
The discussion from the original spin forum post seems to conclude this is more of a bug than intended behavior...

> without looking into the details of this -- doesn't this simply mean that the error scenario is not weakly fair?
... but the reply above seems to suggest this behavior is expected. Did I miss something here?

**Comment by nimble-code** [comment]
note that weak fairness applies only to cyclic executions: infinite executions
at the point where the counter-example is reached (i.e., []( n==2)) both processes have terminated
and can no longer participate in a cyclic execution, hence none are reported
