### ISSUE TITLE
Broken link on spinroot.com

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#39]
I apologize if this is the wrong place to report this, but the link to something called "Tau Tool" (http://authors.library.caltech.edu/56038/) is not working.

**Comment by nimble-code** [comment]
interesting -- I'll make the tool available directly on spinroot

**Comment by jllang** [comment]
Thanks!

**Comment by nimble-code** [comment]
you can download it from: http://spinroot.com/tau_v1.tar.gz 
-g

**Comment by jllang** [comment]
That link seems to also lead into a 404 page.

**Comment by nimble-code** [comment]
sorry, my mistake:  http://spinroot.com/spin/tau_v1.tar.gz

**Comment by jllang** [comment]
Okay, that link works. Thanks!
