### ISSUE TITLE
syntax error shown when passing array to inline ... but works as intended

### ISSUE THREAD

**Issue by NilsPur** [nimble-code/Spin#41]
```
inline test(array)
{
    array[0] = 0;
    array[1] = 3;
    array[2] = 1;
}

active proctype main()
{
    printf("Syntax error shown...\n")
    byte myArray[3];
    test(myArray);
    printf("... but works anyway.\n");
    printf("Array: %d %d %d\n", myArray[0], myArray[1], myArray[2]);
}
```
**OUTPUT**
 Error: missing array index for 'myArray' saw '')' = 41'
Syntax error shown...
 ... but works anyway.
Array: 0 3 1

**Comment by nimble-code** [comment]
interesting.  will look into it

**Comment by nimble-code** [comment]
updated Src/spin.y and Src/version.h to remove the error report when an array name is used in an argument list
thanks for catching this!
-g
