### ISSUE TITLE
pan formats mtype constants as floating point numbers

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#42]
Consider the following model, let's call it `printf.pml`:
```
mtype = { FOO, BAR }

init
{
  printf("%e\n", FOO);
  assert(false)
}
```

If I run it with Spin, I get the following output
```
      FOO
spin: printf.pml:6, Error: assertion violated
spin: text of failed assertion: assert(0)
#processes: 1
  2:	proc  0 (:init::1) printf.pml:6 (state 2)
1 process created
```

I compiled and ran the model with the following commands:

1. `spin -a printf.pml`
2. `gcc -o pan pan.c`
3. `./pan`

Naturally, `pan` finds one error. When I run `./pan -S`, I get the following output:
```
5.059232e-319
pan:1: assertion violated 0 (at depth 1)
spin: trail ends after 1 steps
#processes 1:
  1:	proc 0 (:init:)  printf.pml:5 (state  1) (invalid end state)
		printf('%e\n',FOO)
global vars:
	mtype  FOO:	2
	mtype  BAR:	1
```

Why does `spin` print `FOO`, but `pan` prints `5.059232e-319`?

**Comment by jllang** [comment]
Could it be that `pan` calls the `printf` of the C language?

**Comment by nimble-code** [comment]
Interesting!! I'll check it out.
Pan doesn't call the C printf unless it's enclosed in a c_code { .. } fragment in the spec.

**Comment by nimble-code** [comment]
I cannot reproduce it!  it must be something else.
my runm after "spin -run bug.pml" reports the error:
$ spin -replay bug.pml
      FOO
spin: bug.pml:6, Error: assertion violated
spin: text of failed assertion: assert(0)
spin: trail ends after 1 steps
#processes: 1
  1:    proc  0 (:init::1) bug.pml:7 (state 3) <valid end state>
1 process created

and the same command you did produces:

$ ./pan
pan:1: assertion violated 0 (at depth 0)
pan: wrote bug.pml.trail

(Spin Version 6.5.1 -- 3 June 2021)
Warning: Search not completed
        + Partial Order Reduction

Full statespace search for:
        never claim             - (none specified)
        assertion violations    +
        cycle checks            - (disabled by -DSAFETY)
        invalid end states      +

State-vector 12 byte, depth reached 0, errors: 1
        1 states, stored
        0 states, matched
        1 transitions (= stored+matched)
        0 atomic steps
hash conflicts:         0 (resolved)

Stats on memory usage (in Megabytes):
    0.000       equivalent memory usage for states (stored*(State-vector + overh
ead))
    0.292       actual memory usage for states
  128.000       memory used for hash table (-w24)
    0.534       memory used for DFS stack (-m10000)
  128.730       total actual memory usage



pan: elapsed time 0.503 seconds
pan: rate 1.9880716 states/second

**Comment by jllang** [comment]
Did you try also the -S flag of pan?

**Comment by nimble-code** [comment]
Ah, yes, that shows the floating point -- interesting!!
I'll see if I can nail that down.
thanks

**Comment by nimble-code** [comment]
yup, with ./pan -S the printf gets interpreted by C, as you thought,
and the %e format specifier is then interpreted as type  double....
