### ISSUE TITLE
Spin -I produces malformed output from init process

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#45]
Consider the following model (I call it `test.pml`):
```
init
{
  printf("foo\n")
}
```
This model behaves pretty much as one would expect:
```
$ spin test.pml 
      foo
1 process created
```

If I preprocess the model using the `-I` flag, I get the following output:
```
$ spin -I test.pml > test2.pml && cat test2.pml 
proctype :init:()
{
   printf('foo\\n');
}
```

Now, if I try to run this preprocessed model, I get syntax errors:
```
$ spin test2.pml 
spin: test2.pml:1, Error: syntax error	saw '':' = 58'
spin: test2.pml:3, Error: character quote missing: '
```

The documented grammar of PROMELA does not seem to allow colons in process names. Maybe the `init` process is special?

**Comment by nimble-code** [comment]
will look into all the issues you reported
(just back from short vacation)

**Comment by nimble-code** [comment]
The observation is correct of course, but the result of inlining isn't meant to be valid input at all -- it's just meant to be used as a debugging option to figure out what exactly happens during this process. (I agree that this could be documented in a more prominent place somewhere, right now it appears only in the Updates file from when it was added (Doc/V4.Updates on github) where it says:
- new spin command-line option -I, to reproduce a version of the
  specification after preprocessing and inlining operations are
  done.  the reproduced code is not complete: declarations and
  process parameters are skipped, some internally generated labels
  and jumps (e.g., replacing break statements) also become visible.
  the version is intended only to show what the effect of inlining
  and preprocessing is.
