### ISSUE TITLE
The aliases for LTL binary operators && and || don't seem to work

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#46]
Consider the following model, let's call it `model.pml`:
```
ltl prop1 { x == 1 /\ y == 1 }
ltl prop2 { x == 1 \/ y == 1 }

int x, y;

init
{
  x = 1;
  y = 2;
}
```

Spin doesn't seem to recognise the aliases `/\` and `\/` for `&&`and `||` respectively, even if they're documented in Spin online reference (https://spinroot.com/spin/Man/ltl.html):
```
$ spin model.pml 
spin: model.pml:11, Error: syntax error	saw ''\' = 92'
spin: model.pml:12, Error: syntax error	saw ''\' = 92'
1 process created
```

**Comment by jllang** [comment]
By the way, just out of curiosity: Why doesn't `&&` and `||` have aliases `and` and `or` respectively? Other LTL operators and connectives can be written out using English words.

**Comment by nimble-code** [comment]
Agreed, this wasn't parsed correctly.  I've updated spinlex.c to fix this.
(also a small unrelated change in tl_main.c)
thanks for reporting!
