### ISSUE TITLE
The -k flag is undocumented in Spin Online Reference

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#49]
I noticed that `spin --help` lists the flag `-k`:
```
	-k fname use the trailfile stored in file fname, see also -t
```
It seems that this flag is missing from the online reference: <https://spinroot.com/spin/Man/Spin.html>

**Comment by jllang** [comment]
There's also the `-I` flag:
```
	-I show result of inlining and preprocessing
```
This seems to be missing as well.

**Comment by nimble-code** [comment]
thanks -- both added
