### ISSUE TITLE
Obtaining the changes to variables from a trace

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#50]
Is it possible to obtain the list of local and global variables that changed during a step in a trace?

Here's an excerpt of one of my traces (I used the flags `-p -b -l -g -k`):
```
  4:	proc  0 (:init::1) ./Thread.pml:166 (state 24)	[commands[i] = CONTINUE]
		states[0] = READY
		states[1] = 0
		states[2] = 0
		commands[0] = CONTINUE
		commands[1] = 0
		commands[2] = 0
		serialize_commands = 1
  4:	proc  0 (:init::1) Supervisor.pml:260 (state 27)	[i = (i+1)]
		states[0] = READY
		states[1] = 0
		states[2] = 0
		commands[0] = CONTINUE
		commands[1] = 0
		commands[2] = 0
		serialize_commands = 1
		:init:(0):i = 1
  4:	proc  0 (:init::1) Supervisor.pml:264 (state 31)	[.(goto)]
		states[0] = READY
		states[1] = 0
		states[2] = 0
		commands[0] = CONTINUE
		commands[1] = 0
		commands[2] = 0
		serialize_commands = 1
		:init:(0):i = 1
```

Between the steps, Spin prints values for some local and global variables that didn't change. What I'd like to have, would be the following:

```
  4:	proc  0 (:init::1) ./Thread.pml:166 (state 24)	[commands[i] = CONTINUE]
		commands[0] = CONTINUE
  4:	proc  0 (:init::1) Supervisor.pml:260 (state 27)	[i = (i+1)]
		:init:(0):i = 1
  4:	proc  0 (:init::1) Supervisor.pml:264 (state 31)	[.(goto)]
```

Is it possible to achieve this with some combination of flags? If not, would this be a reasonable feature to request in a future version of Spin?

**Comment by jllang** [comment]
Having these values that didn't changed listed between steps can make the trace considerably more verbose. For instance, I have a trace of 134 steps. If I use the flags `-b -p -v -k`, I get 659 lines of output. If I add the flags `-l -g`, I get 6686 lines, which is more than ten times longer than without those flags. If it were possible to have only the changing variables listed, then the output would stay well below 1000 lines. I imagine that this might become an issue with models having lots of variables and long traces. The size of the output could easily become dozens of megabytes or so.

**Comment by jllang** [comment]
Output size is a consideration for me because I'm working on a server-client style web application for using Spin.

**Comment by nimble-code** [comment]
It's quite a reasonable thing to want, but I'm hesitant to open up that code.  The same effect could be achieved with a small awk- or python- script that reads the raw trailfile and then creates a more condensed version locally. But maybe that's not really feasible in the context your using this?

**Comment by jllang** [comment]
Well, I could keep track of the latest known values of all variables in a hash map and omit those equations that don't give me new information. I just thought it might be more efficient to implement this on the Spin side, but I can definitely do it myself in my application.
