### ISSUE TITLE
Listing all variable values in the beginning of a trace

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#51]
Is it possible to get a list of all (global and local) variable values in the beginning of a trace when using the playback feature with the `-k` flag? If not, I'd like to humbly request a new flag for this. I'm working on a tool that processes traces and it'd be great if I could first have a list of all values of variables and then only seeing the changes after each step of execution (for which I opened the separate issue #50).

**Comment by nimble-code** [comment]
similar to the related question: a small preprocessing script could mine the verbose trailfile for this info and than make it available to your tool, together with the condensed version of the trail?

**Comment by jllang** [comment]
Where can I find documentation for trail files?

**Comment by nimble-code** [comment]
ah - those trailfiles were never meant to be human-readable.
the basic format is a sequence of 3 numbers separated by colons:
one line for each execution step along the trail:
   step number, process id, transition id, 
and then there are special lines with negative numbers,
typically at the start or end of the trail
-1:-1:-1  marks the start of a cycle
-2:N:-2 records the presence of a never claim N
-4:-4:-4 defines that the verification used statement merging
-5:N:M  defines that a permuted search order was used
-6:N:M defines that process reordering was used
-7:N:M defines that process order rotation was used
-8:N:M defines that random process order rotation was used
the latter set (-5 and smaller) are rare cases of course
I'd have to dig through the code to get more details on the
precise meanings of the N and M's in each case though

**Comment by jllang** [comment]
Thanks for the info!

**Comment by jllang** [comment]
In order to interpret a trail file, I'd need to know where transition IDs come from. Perhaps I could infer the starting states of variables by running static analysis on the PROMELA file. I'm under the impression that variables without declared initial values will be initialised to zeros. Otherwise, their initial value will be whatever was given in the code. For example,
```
int x;     /* Will be 0 initially */
int y = 7; /* Will be 7 initially */
```
Is this really that simple or are there something else I need to take into consideration as well?

**Comment by nimble-code** [comment]
the transition id's are from the underlying statemachine representations.
you can display them with the -d  command on the pan verifiers -- or directly from spin as:

$ spin -run -d ex.pml
init
        state   1 -(tr   3)-> state   7  [id   0 tp   2] [----L] ex.pml:9 => i = 0
        state   7 -(tr   4)-> state   7  [id   1 tp   2] [----L] ex.pml:9 => ((i<=3))
        state   7 -(tr   2)-> state  10  [id   4 tp   2] [----L] ex.pml:9 => else
        state  10 -(tr   5)-> state   0  [id   9 tp 3500] [--e-L] ex.pml:12 => -end-

Transition Type: A=atomic; D=d_step; L=local; G=global
Source-State Labels: p=progress; e=end; a=accept;
Note: statement merging was used. Only the first
      stmnt executed in each merge sequence is shown
      (use spin -a -o3 to disable statement merging)

**Comment by nimble-code** [comment]
but, yes, the initial value of all objects is zero or empty (channels), unless and explicit initial value is specified

**Comment by jllang** [comment]
Thanks again for the info! 

It seems that this static analysis approach I planned isn't quite as trivial as I expected it to be. Firstly, I don't know how to infer the channel identifiers (I assume it's the number that matters and not the name of the variable that refers to a channel). Secondly, for local variables there's the questions that do they even exist before the process is instantiated using a `run` expression. Inferring reliably when and what arguments are passed to processes seems like a deep rabbit hole.

I think I'll just grab the initial values for global variables from the code and leave channels and local variables in an "unknown" initial state.
