### ISSUE TITLE
Documentation of unsigned values

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#52]
The keyword `unsigned` is missing from the list at <https://spinroot.com/spin/Man/promela.html>. The syntax for `unsigned` declarations is not specified in the grammar page <https://spinroot.com/spin/Man/grammar.html>. (There is a mention of unsigned values in <https://spinroot.com/spin/Man/datatypes.html> though.) From what I've gathered during my empirical experimentations is that the syntax might be something like this:
```ebnf
unsigned declaration   = 'unsigned',
                         initial unsigned value,
                         { ',', initial unsigned value };
initial unsigned value = variable name,
                         ':',
                         positive integer,
                         [unsigned value];
unsigned value         = '=', expression;
```
Is this syntax correct? If so, perhaps it could be added to the documentation.

**Comment by nimble-code** [comment]
the description can be found in the manual page for datatypes:
  http://spinroot.com/spin/Man/datatypes.html
but you're right that it should also appear in the grammar description

**Comment by nimble-code** [comment]
I've updated the grammar.html page
