### ISSUE TITLE
Printm

### ISSUE THREAD

**Issue by jllang** [nimble-code/Spin#55]
This is jsut a minor remark, but I just noticed that the manual page of `printf` mentions another version named `printm`. Does `printm` really support arbitrary expressions? The prose in Spin online reference and the actual behaviour of Spin seems to suggest that it'd be reasonable to restrict the argument of `printm` to `mtype` values.

**Comment by nimble-code** [comment]
Good point -- the use of 'expression' in the manual page was incorrect.
I replaced it with 'name'  since the argument is expected to be an mtype constant.
Thanks for catching that!
