### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by AiDaiP** [nimble-code/Spin#58]
I have a lot of crashes but I have no time to analysis them all because I have a final exam recently.
Should I upload them here or send them to you by email?

**Comment by AiDaiP** [comment]
.
├── for_index-yyparse
│   └── id:000331,sig:11,src:002085+001171,op:splice,rep:16
├── __GI_raise-__GI_abort
│   ├── id:000000,sig:06,src:001299+001424,op:splice,rep:2
│   ├── id:000008,sig:06,src:001424+001304,op:splice,rep:32
│   ├── id:000010,sig:06,src:001499,op:havoc,rep:32
│   ├── id:000012,sig:06,src:001593,op:havoc,rep:8
│   ├── id:000014,sig:06,src:001593+000821,op:splice,rep:32
│   ├── id:000017,sig:06,src:001595,op:havoc,rep:32
│   ├── id:000018,sig:06,src:001595,op:havoc,rep:128
│   ├── id:000024,sig:06,src:001660+000136,op:splice,rep:16
│   ├── id:000038,sig:06,src:001709+001655,op:splice,rep:64
│   ├── id:000041,sig:06,src:001712,op:havoc,rep:64
│   ├── id:000044,sig:06,src:001748,op:havoc,rep:16
│   ├── id:000045,sig:06,src:001748,op:havoc,rep:64
│   ├── id:000049,sig:06,src:001020+001745,op:splice,rep:64
│   ├── id:000055,sig:06,src:001802+001597,op:splice,rep:2
│   ├── id:000058,sig:06,src:001840,op:havoc,rep:64
│   ├── id:000061,sig:06,src:001840+001838,op:splice,rep:64
│   ├── id:000064,sig:06,src:001864,op:havoc,rep:128
│   ├── id:000065,sig:06,src:001864,op:havoc,rep:64
│   ├── id:000071,sig:06,src:001871,op:havoc,rep:128
│   ├── id:000073,sig:06,src:001888,op:havoc,rep:32
│   ├── id:000077,sig:06,src:001895,op:havoc,rep:16
│   ├── id:000158,sig:11,src:000002+002040,op:splice,rep:8
│   ├── id:000159,sig:11,src:000393+001998,op:splice,rep:8
│   ├── id:000161,sig:11,src:001567+001998,op:splice,rep:64
│   ├── id:000181,sig:11,src:002291+001584,op:splice,rep:128
│   ├── id:000214,sig:11,src:002450,op:havoc,rep:32
│   ├── id:000245,sig:06,src:002675+000728,op:splice,rep:16
│   ├── id:000319,sig:11,src:003161,op:havoc,rep:8
│   ├── id:000329,sig:11,src:003191+002882,op:splice,rep:128
│   ├── id:000335,sig:11,src:003231,op:havoc,rep:16
│   ├── id:000355,sig:11,src:002973+003114,op:splice,rep:64
│   └── id:000362,sig:11,src:002992+002696,op:splice,rep:32
├── _IO_getc-Getchar
│   ├── id:000095,sig:11,src:001694,op:havoc,rep:32
│   ├── id:000107,sig:11,src:001613+000891,op:splice,rep:8
│   ├── id:000112,sig:11,src:001941,op:havoc,rep:32
│   ├── id:000113,sig:11,src:001941+001757,op:splice,rep:32
│   ├── id:000131,sig:11,src:002070+001964,op:splice,rep:128
│   └── id:000175,sig:11,src:002275+001592,op:splice,rep:8
├── _IO_new_fclose-main
│   └── id:000094,sig:11,src:001694,op:havoc,rep:64
├── ismtype-lex
│   ├── id:000084,sig:11,src:000410+000363,op:splice,rep:128
│   ├── id:000085,sig:11,src:001127,op:havoc,rep:32
│   ├── id:000110,sig:11,src:001750,op:havoc,rep:16
│   ├── id:000122,sig:11,src:002034+001359,op:splice,rep:4
│   ├── id:000132,sig:11,src:002097,op:havoc,rep:16
│   ├── id:000144,sig:11,src:002157,op:havoc,rep:128
│   ├── id:000167,sig:11,src:001488,op:havoc,rep:16
│   ├── id:000174,sig:11,src:002273,op:havoc,rep:8
│   ├── id:000186,sig:11,src:002311+000456,op:splice,rep:16
│   ├── id:000194,sig:11,src:002347+001048,op:splice,rep:128
│   ├── id:000198,sig:11,src:002366,op:havoc,rep:16
│   ├── id:000209,sig:11,src:002415,op:havoc,rep:16
│   ├── id:000220,sig:11,src:002477+002457,op:splice,rep:32
│   ├── id:000224,sig:11,src:002490,op:havoc,rep:64
│   ├── id:000236,sig:11,src:002605,op:havoc,rep:32
│   ├── id:000271,sig:11,src:002845+000474,op:splice,rep:16
│   ├── id:000272,sig:11,src:002853,op:havoc,rep:128
│   ├── id:000301,sig:11,src:003072,op:havoc,rep:32
│   ├── id:000318,sig:11,src:003099+001137,op:splice,rep:32
│   ├── id:000403,sig:11,src:000727,op:havoc,rep:16
│   ├── id:000408,sig:11,src:001309,op:havoc,rep:16
│   └── id:000409,sig:11,src:002943,op:havoc,rep:128
├── non_fatal-fatal
│   ├── id:000106,sig:11,src:001550+001533,op:splice,rep:128
│   ├── id:000142,sig:11,src:002138+001753,op:splice,rep:128
│   ├── id:000253,sig:11,src:002718,op:havoc,rep:16
│   ├── id:000292,sig:11,src:002858,op:havoc,rep:64
│   ├── id:000316,sig:11,src:001625,op:havoc,rep:64
│   └── id:000407,sig:11,src:001215+003332,op:splice,rep:16

**Comment by nimble-code** [comment]
These reports aren't very useful, since they seem to go well outside the domain of application of Modex.
You did find some interesting cases earlier, but perhaps we've reached the limits of what the fuzzer can locate sensibly.
