### ISSUE TITLE
On macOS Monterey 12.4 with Dark theme there are buttons with unreadable labels (white text on white background)

### ISSUE THREAD

**Issue by varosi-chaosgroup** [nimble-code/Spin#59]
On macOS Monterey 12.4 with Dark theme there are buttons with unreadable labels (white or yellow text on white background).
See this screenshot:
<img width="1200" alt="Screenshot 2022-05-26 at 17 10 51" src="https://user-images.githubusercontent.com/31626390/170504951-0dbbdf99-4b28-4b88-9377-a457e4b01f90.png">

SPIN installed with: brew install spin
iSpin got from the latest master branch of this repo.

**Comment by nimble-code** [comment]
thanks for reporting -- will check it out

**Comment by nimble-code** [comment]
interesting -- the background color for those buttons is explicit set to darkblue
in the ispin app (color NBG which is defined as darkblue on line 91)
how does the os manage to override that....

**Comment by varosi-chaosgroup** [comment]
I have no idea. May be it could be other property that is taken into account? Or some defaults.

**Comment by varosi-chaosgroup** [comment]
I may test here any change that you make.

**Comment by varosi-chaosgroup** [comment]
<img width="1200" alt="Screenshot 2022-11-10 at 23 06 12" src="https://user-images.githubusercontent.com/31626390/201205874-6cc215fa-8bfc-4f51-bc32-d2bd9ebe0ac6.png">

**Comment by varosi-chaosgroup** [comment]
This is on the latest macOS 13.0.

**Comment by nimble-code** [comment]
it's not a system I use, so I cannot test this, but the colors of most of the buttons can be changed in the tcl/tk source
if you find the Label-name, for instance, and look at how bg and fg are set, you can pick a color setting that works better for you
-g

**Comment by c-kloukinas** [comment]
I've installed tcl-tk with brew (brew install tcl-tk) and then added that version ahead of my path (in Bash):
`export PATH=/usr/local/opt/tcl-tk/bin/:"${PATH}"`

After doing so, the colours are *much* better than when using the default wish installed by Apple in /usr/bin...
(some blue background with gold text)

Not at all sure why Apple's wish ignores the colours, while the one from Brew respects them.

(**Note:** Brew doesn't install tcl-tk into /usr/local/bin by default, so as not to clash with what Apple provides - lets you make this choice explicitly by changing your PATH. So it's not enough to simply install it with brew, you need to change your path as well - e.g., in your ~/.profile )

**Comment by nimble-code** [comment]
interesting!  thanks for the update!
