### ISSUE TITLE
Error using mtype:name in typedef

### ISSUE THREAD

**Issue by albertnetymk** [nimble-code/Spin#6]
Encountered some errors while using `mtype`. Google led me to http://spinroot.com/fluxbb/viewtopic.php?id=1628, but I can't post a reply there. (No new users can register.)

The following is the failing example, and the error I got is "Error: 'obj' is type 'color' but 'Round' is type 'shape'". I would expect the example to work after reading the manual on `typedef` and `mtype`. Using version 6.4.9.
```
mtype:color = {White, Black}
mtype:shape = {Round, Square}

typedef Obj {
  mtype:color c
  mtype:shape s
}

init {
  Obj obj;
  obj.c = White
  obj.s = Round
}
```

**Comment by raphj** [comment]
Yes, I found using two mtypes in a typedef was problematic.

This works:

```
mtype:color = {White, Black}

#define shape_t byte
#define Round 1
#define Square 2

typedef Obj {
  mtype:color c
  shape_t s
}

init {
  Obj obj;
  obj.c = White
  obj.s = Round
}
```

This works too:

```
mtype:color = {White, Black}

#define color_t byte
#define White 1
#define Black 2

mtype:shape = {Round, Square}

typedef Obj {

  color_t c
  mtype:shape s
}

init {
  Obj obj;
  obj.c = White
  obj.s = Round
}
```

And this works too:

``
mtype:color = {White, Black}
mtype:shape = {Round, Square}

typedef Obj {
  mtype:color c1
  mtype:color c2
}

init {
  Obj obj;
  obj.c1 = White
  obj.c2 = Black
}
```

This also works:

```
mtype:color = {White, Black}
mtype:shape = {Round, Square}

typedef Obj1 {
  mtype:color c
}

typedef Obj2 {
  mtype:shape s
}


init {
  Obj1 o1;
  Obj2 o2;
  o1.c = White
  o2.s = Round
}
```

This looks like a bug where one of the field is assigned the incorrect type if there are two different mtype:stuff types used in one typedef.

**Comment by albertnetymk** [comment]
Thanks for the confirming the behavior; I will use the first workaround for now.

**Comment by nimble-code** [comment]
made small update to mesg.c to avoid the bug.
for now it means though that assignments of mtype values to structure fields aren't typechecked (they weren't before either), but at least this erroneous warning is no longer generated

**Comment by albertnetymk** [comment]
Works with the last commit. Thank you very much.
