### ISSUE TITLE
Is there any way to initialize custom `typedef` variables

### ISSUE THREAD

**Issue by hzyrc6011** [nimble-code/Spin#66]
For example, here is the struct I defined:
```promela
typedef SimData{
    int current_step;
    int model_state;
}
```
To initialize it, I could only do by these code:
```promela
int current_step = 1;
int model_state = 2;
SimData sd;
sd.current_step = current_step;
sd.model_state = model_state;
```
Is there any way to initialize custom variable within one line, as shown in the following image? I have read the documentation, and googled this problem, but nothing was found. Thanks a lot!

<img width="353" alt="image" src="https://github.com/nimble-code/Spin/assets/36789453/2367e746-4680-4b38-bc93-e6c6c9cb78a3">

**Comment by nimble-code** [comment]
No there currently is no way to do a compound initialization of a typedef in Promela
