### ISSUE TITLE
Verification of a model with many printf statements has a floor verification time of ~30 seconds

### ISSUE THREAD

**Issue by brycepierson** [nimble-code/Spin#69]
It was my understanding until recently that printf statements were mostly treated as "skip" statements during verification. I've since learned that there is technically a possibility to modify variables or run additional processes from within printf arguments, so they must be evaluated. However, it feels like something weird is going on when my model takes ~30 seconds to verify with the printf statements in but ~2 seconds once I take them out. is 28 seconds of evaluation happening? My printf statements are relatively simple, and I am not doing any side effecting with them. It's true that I have around ~1200 (after inlines are expanded) but evaluating that many doesn't seem like it would take 28 seconds. Am I missing something?

**Comment by nimble-code** [comment]
yes, that's interesting and unexpected.
you could try to profile the run, to see where the time is going.
can you share the model?

**Comment by brycepierson** [comment]
Unfortunately I'm relatively new to spin, so I'm not sure how to profile the run.

I'll attach two files here. They are equivalent models, except for the `printfModel.pml` one has the printf statements added.

Also, I apologize, my initial numbers were in reference to a different set of models. The change here is ~2 seconds to ~17 seconds. Not as significant but still concerning.

Files are renamed to be TXT files to comply with github.
[model.txt](https://github.com/nimble-code/Spin/files/12667917/model.txt)
[printfModel.txt](https://github.com/nimble-code/Spin/files/12667918/printfModel.txt)

**Comment by nimble-code** [comment]
I imagine most if not all the difference is caused by the calls to logState in the printModel version -- there's quite a bit of work happening there, even though nothing gets printed

**Comment by brycepierson** [comment]
Interesting. I see you're correct, as I built an additional model with all the `printf()` statements replaced with `skip`. It still took ~17 seconds to run. It seems surprising to me that skips in an atomic block can add so much to run time without doing anything. I even removed all of the if statements in logState and it still adds 4-5 seconds to run time.

**Comment by brycepierson** [comment]
My problem was alleviated by replacing the atomic block in logState() with a d_step block. After thoroughly reading the spinroot entries for both atomic and d_step, it is clear that d_step is what I was after originally. Thanks for your help!
