### ISSUE TITLE
Typo in Man/Intro.html

### ISSUE THREAD

**Issue by rillig** [nimble-code/Spin#71]
The file `Man/html_manual_pages.tar.gz/Intro.html` says:
> A sixt section gives a brief motivation

The word _sixt_ should be _sixth_.

I would have sent a pull request, but I was unsure why the manual pages are in an archive instead of being directly editable and what the best way would be to fix typos in them.

**Comment by nimble-code** [comment]
updated (sorry that took so long!)

**Comment by rillig** [comment]
How did you fix it? The file [html_manual_pages.tar.gz](https://github.com/nimble-code/Spin/tree/8e9a00d2342387dbce2c07519ebf4d2a98ef9236/Man) is still listed as "5 years ago".

**Comment by nimble-code** [comment]
not in the tar file -- but in the online page at spinroot.com/spin/Man/Intro.html
