### ISSUE TITLE
Better printf support for multiple mtype and multiple %e

### ISSUE THREAD

**Issue by melintea** [nimble-code/Spin#74]
Please see below two tests. For both, it would be nice if printf result would be: `event: _e=two _f=pear _s=large _i=101`

// stest1  ---------------------------------------------------------------------
mtype:num   = { one, two, three };
mtype:fruit = { appel, pear, banana };
mtype:sizes = { small, medium, large };
typedef event { mtype:num _e; mtype:fruit _f; mtype:sizes _s; int _i; };

inline send_event(t1, f, s, i)
{
    local event evt;
    evt._e = t1;
    evt._f = f;
    evt._s = s;
    evt._i = i;

    // result: event: _e=2 _f=2 _s=1 _i=101
    printf("event: _e=%e _f=%e _s=%e _i=%e\n", evt._e, evt._f, evt._s, evt._i);
}

active proctype print_test()
{
    send_event(two, pear, large, 101);
}

// test2  ---------------------------------------------------------------------
mtype   = { one, two, three }; // <==  diff from test1
mtype:fruit = { appel, pear, banana };
mtype:sizes = { small, medium, large };
typedef event { mtype:num _e; mtype:fruit _f; mtype:sizes _s; int _i; };

inline send_event(t1, f, s, i)
{
    local event evt;
    evt._e = t1;
    evt._f = f;
    evt._s = s;
    evt._i = i;

    // event: _e=two _f=two _s=three _i=101
    printf("event: _e=%e _f=%e _s=%e _i=%e\n", evt._e, evt._f, evt._s, evt._i);
}

active proctype print_test()
{
    send_event(two, pear, large, 101);
}

**Comment by nimble-code** [comment]
confirmed -- an even simpler example is this:
mtype     = { alpha, beta, gamma }	// needs at least 2 elements...
mtype:num = { one, two, three }

active proctype test()
{
	printf("%e\n", two) // prints: beta
	// without first line, prints: 2
}

**Comment by nimble-code** [comment]
I've updated the code to fix the examples.
Hopefully it didn't break anything else.
(It's been a while since I updated the code.)

**Comment by melintea** [comment]
Thank you!
