### ISSUE TITLE
Windows amd64 distributions might be containing 32bit executable

### ISSUE THREAD

**Issue by h-mole** [nimble-code/Spin#76]
Thanks for this awesome work!  But I am having a little problem on windows distributions.

When I am trying the spin tool on windows cygwin 64bit following the instructions in the docs, I downloaded the file from https://github.com/nimble-code/Spin/blob/master/Bin/spin651_windows64.exe.gz whose name indicates it was an amd64 distribution.
However, this file does not work normally in my cygwin environment, and the pan.exe reports `spin: error, the version of spin that generated this pan.c assumed a different wordsize (4 iso 8)`.

I opened the file `spin651_windows64.exe` by notepad, and found that it is showing `PE L`, which means though the file name indicates 64bit, it was a 32bit distribution in actual fact. To solve this, I compiled spin under cygwin with the `make` command, and the generated spin file worked normally.

![image](https://github.com/user-attachments/assets/8f3fe703-b0af-43fc-9559-84abd059a8da)

Would you mind re-upload a new 64-bit version for spin distribution? Thanks for your awesome work again!

**Comment by nimble-code** [comment]
I added a new executable for 652 in the Bin directory
hopefully a correct 64 bit executable
