### ISSUE TITLE
LTL expressions are not parsed on Windows

### ISSUE THREAD

**Issue by ichitera** [nimble-code/Spin#8]
When I passed `Examples/LTL/bakery.pml`, which included an LTL formula, to Spin, Spin showed  `ltl invariant: (null)` and crashed. It seemed that the LTL formula was not parsed correctly.

I executed Spin as follows on the root directory of this project:

1. `Bin\spin650_windows64.exe Examples\LTL\bakery.pml`
![image](https://user-images.githubusercontent.com/31098747/61259215-2fd5bf80-a7b4-11e9-8583-c6398cdaadf9.png)

(NOTE: spin650_windws64.exe is the file extracted from spin650_windows64.exe.gz)

**Environment:**

* OS: Windows 10 (64bit)
* Spin: 6ad4b2555e8cf77d4636c576755f2b0fd89869ce

**Comment by nimble-code** [comment]
yes, I can reproduce that.  if I look with gdb it complains about incompatible shared libraries, so i may not have compiled that properly with mingw
best to compile spin from sources in your case, (type 'make' in the Src directory), to make sure it'll work.
i'll try to figure out how else this should be compiled

**Comment by ichitera** [comment]
Thank you for the reply. I found some problems in the source code. I will share the problems.

**Problem 1:** a mistake of pointer handling

https://github.com/nimble-code/Spin/blob/6ad4b2555e8cf77d4636c576755f2b0fd89869ce/Src/main.c#L872-L878

I think L876 should be `*lineptr = (char *) &buffer;`.

**Problem 2:** a static array is freed

The implementation of `getline` requires the follows (I think that you already know):
> If *lineptr is NULL, then getline() will **allocate a buffer** for storing the line, **which should be freed** by the user program. (In this case, the value in *n is ignored.)

(cited from: https://linux.die.net/man/3/getline, and emphasized by me)

The current implementation of `getline` in main.c uses a statically allocated array (in L874 of the above code), and the static array is passed to `free()` (L1098 in the following code).

https://github.com/nimble-code/Spin/blob/6ad4b2555e8cf77d4636c576755f2b0fd89869ce/Src/spin.y#L1085-L1098

**Comment by nimble-code** [comment]
Thank you very much -- both embarrassing bugs.
I've made the corrections, and confirmed that the bakery.pml example now works.
(For the second problem, I made sure that with a MINGW compilation that call to free is not executed.)
Thank you!
